[package]
name = "chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

array-init = "2.0.0"
termion = "1.5.6"
rand = "0.8.5"
rayon = "1.5.3"